### ISSUE TITLE
Error with Unite 1.1.7

### ISSUE THREAD

**Issue by editon96** [PikaMug/Unite#4]
Hey I use Purpur 1.19.4 a fork of Paper

```
[10:38:45] [Server thread/INFO]: [Unite] Enabling Unite v1.1.7
[10:38:45] [Server thread/INFO]: [Unite] [Party] mcMMO found: Loaded
[10:38:45] [Server thread/ERROR]: Error occurred while enabling Unite v1.1.7 (Is it up to date?)
java.lang.NoClassDefFoundError: de/simonsator/partyandfriends/spigot/api/events/BridgeNotAvailableException
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3373) ~[?:?]
	at java.lang.Class.getConstructor0(Class.java:3578) ~[?:?]
	at java.lang.Class.getConstructor(Class.java:2271) ~[?:?]
	at me.pikamug.unite.Unite.hookProvider(Unite.java:70) ~[95217 - Unite.jar:?]
	at me.pikamug.unite.Unite.hookProviders(Unite.java:63) ~[95217 - Unite.jar:?]
	at me.pikamug.unite.Unite.onEnable(Unite.java:32) ~[95217 - Unite.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:570) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:481) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:643) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:442) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:345) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1120) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1974]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: de.simonsator.partyandfriends.spigot.api.events.BridgeNotAvailableException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.19.4-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 19 more
[10:38:45] [Server thread/INFO]: [Unite] Disabling Unite v1.1.7
```

It looks like the new Intigation from Party and Friends Extended dont work.

**Comment by PikaMug** [comment]
@editon96 Which version number of Party and Friends do you have installed?
